# Full LXC/MicroK8s playbook — robust worker install, dynamic user, join, labeling

# -----------------------------
# Controller Setup
# -----------------------------
- name: Install and configure MicroK8s on controller
  hosts: k8scontroller
  become: yes
  gather_facts: yes
  vars:
    microk8s_addons:
      - dns
      - storage
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      ignore_errors: yes

    - name: Install snapd
      apt:
        name: snapd
        state: present
      ignore_errors: yes

    - name: Ensure snapd service is running
      systemd:
        name: snapd
        state: started
        enabled: yes
      ignore_errors: yes

    - name: Install AppArmor
      apt:
        name: apparmor
        state: present
      ignore_errors: yes

    - name: Install MicroK8s
      community.general.snap:
        name: microk8s
        classic: yes
        state: present
      ignore_errors: yes

    - name: Add AppArmor reload cron job on reboot
      cron:
        name: "MicroK8s AppArmor reload"
        special_time: reboot
        job: "/usr/sbin/apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap.microk8s.* > /dev/null 2>&1"
        user: root
      ignore_errors: yes

    - name: Reboot controller if snapd/MicroK8s needs it
      reboot:
        msg: "Reboot for MicroK8s to finalize"
        reboot_timeout: 600
      ignore_errors: yes

    - name: Wait for MicroK8s to be ready
      shell: microk8s status --wait-ready
      retries: 10
      delay: 15
      register: microk8s_ready
      until: microk8s_ready.rc == 0
      ignore_errors: yes

    - name: Get remote $USER
      command: echo $USER
      register: remote_user
      ignore_errors: yes

    - name: Add controller user to microk8s group dynamically
      user:
        name: "{{ remote_user.stdout }}"
        groups: microk8s
        append: yes
      ignore_errors: yes

    - name: Enable MicroK8s addons
      command: microk8s enable {{ item }}
      loop: "{{ microk8s_addons }}"
      register: addon_results
      changed_when: "'already enabled' not in addon_results.stdout"
      ignore_errors: yes

# -----------------------------
# Worker Setup — robust LXC install
# -----------------------------
- name: Install MicroK8s on workers
  hosts: k8sworkers
  become: yes
  gather_facts: yes
  serial: 1
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      ignore_errors: yes

    - name: Install snapd
      apt:
        name: snapd
        state: present
      ignore_errors: yes

    - name: Ensure snapd service is running
      systemd:
        name: snapd
        state: started
        enabled: yes
      ignore_errors: yes

    - name: Install AppArmor
      apt:
        name: apparmor
        state: present
      ignore_errors: yes

    - name: Install MicroK8s
      community.general.snap:
        name: microk8s
        classic: yes
        state: present
      ignore_errors: yes

    - name: Add AppArmor reload cron job
      cron:
        name: "MicroK8s AppArmor reload"
        special_time: reboot
        job: "/usr/sbin/apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap.microk8s.* > /dev/null 2>&1"
        user: root
      ignore_errors: yes

    - name: Get remote $USER
      command: echo $USER
      register: remote_user
      ignore_errors: yes

    - name: Add user to microk8s group
      user:
        name: "{{ remote_user.stdout }}"
        groups: microk8s
        append: yes
      ignore_errors: yes

    - name: Reboot worker if snapd/MicroK8s needs it
      reboot:
        msg: "Reboot for MicroK8s to finalize"
        reboot_timeout: 600
      ignore_errors: yes

    - name: Wait for MicroK8s to be ready
      shell: microk8s status --wait-ready
      retries: 10
      delay: 15
      register: microk8s_ready
      until: microk8s_ready.rc == 0
      ignore_errors: yes

# -----------------------------
# Join Workers to Cluster with retries
# -----------------------------
- name: Dynamically join workers to MicroK8s cluster
  hosts: k8sworkers
  become: yes
  gather_facts: no
  serial: 1
  tasks:
    - name: Check if worker is already in cluster
      shell: microk8s kubectl get nodes -o name
      delegate_to: "{{ groups['k8scontroller'][0] }}"
      register: cluster_nodes
      ignore_errors: yes
      retries: 5
      delay: 10
      until: cluster_nodes is defined

    - name: Generate join command on controller for this worker
      shell: microk8s add-node --format short
      delegate_to: "{{ groups['k8scontroller'][0] }}"
      register: join_cmd
      when: inventory_hostname not in cluster_nodes.stdout
      ignore_errors: yes
      retries: 5
      delay: 10
      until: join_cmd is defined and join_cmd.stdout != ""

    - name: Join worker to MicroK8s cluster
      shell: "{{ join_cmd.stdout }} --worker"
      when: inventory_hostname not in cluster_nodes.stdout
      ignore_errors: yes
      retries: 5
      delay: 15
      until: result is defined and result.rc == 0
      register: result

    - name: Label worker node automatically
      shell: microk8s kubectl label node {{ inventory_hostname }} role=worker --overwrite
      delegate_to: "{{ groups['k8scontroller'][0] }}"
      ignore_errors: yes
      retries: 5
      delay: 10
      until: label_result is defined
      register: label_result
