---
- name: Setup Lab
  hosts: lab
  serial: 1
  become: true
  ignore_unreachable: true
  ignore_errors: true
  tasks:
    - name: Ensure firewalld is at the latest version
      ansible.builtin.dnf:
        name: firewalld
        state: present
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux'
      notify:
        - Restart firewalld
    - name: Ensure firewalld is running
      ansible.builtin.service:
        name: firewalld
        state: started
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux'
    - name: Install snapd
      ansible.builtin.apt:
        name: snapd
        state: present
      when: ansible_distribution == 'Ubuntu'
    - name: Install vim using apt
      ansible.builtin.apt:
        name: vim
        state: present
      when: ansible_distribution == 'Ubuntu'
    - name: Install emacs-nox using apt
      ansible.builtin.apt:
        name: emacs-nox
        state: present
      when: ansible_distribution == 'Ubuntu'
    - name: Install vim using dnf
      ansible.builtin.dnf:
        name: vim
        state: present
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux'
    - name: Install less using dnf
      ansible.builtin.dnf:
        name: less
        state: present
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux'
    - name: Pause for 10 seconds
      ansible.builtin.pause:
        seconds: 10
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux'
  handlers:
    - name: Restart firewalld
      ansible.builtin.service:
        name: firewalld
        state: restarted
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux'
