---
- name: Install MicroK8s
  hosts: all
  serial : 1
  become: true
  tasks:
    - name: Install snapd
      apt:
        name: snapd
        state: present

    - name: Install MicroK8s
      shell: snap install microk8s --classic

    - name: Get USER environment variable from remote host
      command: echo $USER
      register: user

    - name: Allow non-root access to MicroK8s
      shell: usermod -aG microk8s akaria

    - name: Configure MicroK8s
      shell: microk8s status --wait-ready

- name: MicroK8s Controller Setup
  hosts: k8scontroller
  serial : 1
  become: true
  tasks:
    - name: MicroK8s Controller enable dns
      shell: microk8s enable dns

    - name: MicroK8s Controller enable hostpath-storage
      shell: microk8s enable hostpath-storage

    - name: MicroK8s Controller deploy sample nginx app
      shell: microk8s kubectl create deployment nginx --image=nginx

    - name: MicroK8s Controller expose sample nginx app
      shell: microk8s kubectl expose deployment nginx --type=NodePort --port=80
