---
- name: Setup Lab
  hosts: lab
  serial : 1
  become: true
  tasks:
    - name: Install snapd
      ansible.builtin.apt:
        name: snapd
        state: present
      when: ansible_distribution == 'Ubuntu'
    - name: Install vim using apt
      ansible.builtin.apt:
        name: vim
        state: present
      when: ansible_distribution == 'Ubuntu'
    - name: Install emacs-nox using apt
      ansible.builtin.apt:
        name: emacs-nox
        state: present
      when: ansible_distribution == 'Ubuntu'
    - name: Install vim using dnf
      ansible.builtin.dnf:
        name: vim
        state: present
      when: ansible_distribution == 'Rocky'
    - name: Install emacs-nox using dnf
      ansible.builtin.dnf:
        name: emacs-nox
        state: present
      when: ansible_distribution == 'Rocky'