---
- name: Setup Lab
  hosts: lab
  serial: 1
  become: true
  ignore_unreachable: true
  ignore_errors: true
  tasks:
    - name: Install bind-utils
      ansible.builtin.yum:
        name: bind-utils
        state: present
    - name: Pause for 5 seconds
      ansible.builtin.pause:
        seconds: 5
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux' or ansible_distribution == 'CentOS'
    - name: Configure Resolve file QEMU
      ansible.builtin.command: nmcli connection modify ens18 ipv4.dns 192.168.1.50
      when: (ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux') and ansible_virtualization_role == 'guest'
    - name: Configure Resolve file Physical
      ansible.builtin.command: nmcli connection modify enp2s0 ipv4.dns 192.168.1.50
      when: (ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux') and ansible_virtualization_role == 'host'
    - name: Configure Resolve file legacy
      ansible.builtin.command: nmcli connection modify eth0 ipv4.dns 192.168.1.50 and ansible_virtualization_role == 'guest'
      when: ansible_distribution == 'CentOS'
    - name: Configure Resolve file LXC
      ansible.builtin.command: nmcli connection modify eth0 ipv4.dns 192.168.1.50 and ansible_virtualization_type == 'lxc'
      when: ansible_distribution == 'CentOS'
    - name: Reboot
      ansible.builtin.reboot:
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux' or ansible_distribution == 'CentOS'

