[k8scontroller1]
type = "container"
image = "ubuntu:22.04"
ram = "8GB"
cpu = 6
protected = 0
secureboot = 1

[k8sworker1]
type = "container"
image = "ubuntu:22.04"
ram = "4GB"
cpu = 4
protected = 0
secureboot = 1

