---
- name: Setup NPRE Clients
  hosts: lab
  serial: 2
  become: true
  ignore_unreachable: true
  ignore_errors: true
  tasks:
    - name: Open firewall port for nrpe
      ansible.posix.firewalld:
        port: 5666/tcp
        immediate: true
        permanent: true
        state: enabled
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux' or ansible_distribution == 'CentOS'
      notify:
        - Restart firewalld
    - name: Install nagios common using dnf
      ansible.builtin.yum:
        name: nagios-common
        state: present
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux' or ansible_distribution == 'CentOS'
    - name: Install nagios nrpe using dnf
      ansible.builtin.yum:
        name: nrpe
        state: present
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux' or ansible_distribution == 'CentOS'
    - name: Install nagios plugins nrpe using dnf
      ansible.builtin.yum:
        name: nagios-plugins-nrpe
        state: present
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux' or ansible_distribution == 'CentOS'
    - name: Install nagios plugins proc using dnf
      ansible.builtin.yum:
        name: nagios-plugins-procs
        state: present
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux' or ansible_distribution == 'CentOS'
    - name: Install nagios plugins users using dnf
      ansible.builtin.yum:
        name: nagios-plugins-users
        state: present
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux' or ansible_distribution == 'CentOS'
    - name: Install nagios plugins load using dnf
      ansible.builtin.yum:
        name: nagios-plugins-load
        state: present
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux' or ansible_distribution == 'CentOS'
    - name: Install nagios plugins disk using dnf
      ansible.builtin.yum:
        name: nagios-plugins-disk
        state: present
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux' or ansible_distribution == 'CentOS'
    - name: Enable NRPE Guest Agent
      ansible.builtin.service:
        name: nrpe
        enabled: true
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux' or ansible_distribution == 'CentOS'
    - name: Allow Nagios to poll via NRPE
      ansible.builtin.replace:
        path: /etc/nagios/nrpe.cfg
        regexp: 'allowed_hosts=127.0.0.1,::1'
        replace: 'allowed_hosts=127.0.0.1,192.168.1.8'
        backup: true
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux' or ansible_distribution == 'CentOS'
      notify:
        - Restart NRPE
    - name: Install nagios check_ssh using yum
      ansible.builtin.yum:
        name: nagios-plugins-ssh
        state: present
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux' or ansible_distribution == 'CentOS'
    - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
      ansible.builtin.file:
        path: /etc/nrpe.d/site_nrpe.cfg
        state: touch
        mode: u=rw,g=r,o=r
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux' or ansible_distribution == 'CentOS'
    - name: Add ssh_check command
      ansible.builtin.lineinfile:
        path: /etc/nrpe.d/site_nrpe.cfg
        line: 'command[check_ssh]=/usr/lib64/nagios/plugins/check_ssh -p 22 127.0.0.1'
        state: present
        create: true
        mode: '644'
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux' or ansible_distribution == 'CentOS'
      notify:
        - Restart NRPE
    - name: Add disk_check command
      ansible.builtin.lineinfile:
        path: /etc/nrpe.d/site_nrpe.cfg
        line: 'command[check_disk]=/usr/lib64/nagios/plugins/check_disk -w 20% -c 10% -p /'
        state: present
        create: true
        mode: '644'
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux' or ansible_distribution == 'CentOS'
      notify:
        - Restart NRPE
    - name: Add total proc check override command for Physical host
      ansible.builtin.lineinfile:
        path: /etc/nrpe.d/site_nrpe.cfg
        line: 'command[check_total_procs]=/usr/lib64/nagios/plugins/check_procs -w 275 -c 300'
        state: present
        create: true
        mode: '644'
      when: >
        (ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux' or ansible_distribution == 'CentOS') and
        ansible_virtualization_role == 'host'
      notify:
        - Restart NRPE
  handlers:
    - name: Restart NRPE
      ansible.builtin.service:
        name: nrpe
        state: restarted
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux' or ansible_distribution == 'CentOS'
    - name: Restart firewalld
      ansible.builtin.service:
        name: firewalld
        state: restarted
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux' or ansible_distribution == 'CentOS'
