# Generated by ChatGPT prompts to convert existing populate_hosts.sh script that resides in the same repository
import os

# Read the contents of the hosts.seed file
with open(os.path.expandvars("hosts.seed"), "r") as f:
    hosts_seed = f.read()

# Write the contents of the hosts.seed file to /etc/hosts
with open("/etc/hosts", "w") as f:
    f.write(hosts_seed)

# Get the output of the lxc list command
lxc_output = os.popen("sudo lxc list -f compact -c 4,n,n").read()

# Split the output into lines and remove the first line
lxc_output_lines = lxc_output.split("\n")[1:]

# Append the remaining lines to /etc/hosts
with open("/etc/hosts", "a") as f:
    for line in lxc_output_lines:
        f.write(line + "\n")