[lab-rocky8-1]
type = "vm"
image = "images:rockylinux/8/cloud"
ram = "2GB"
cpu = 2
protected = 0
secureboot = 1

[lab-rocky8-2]
type = "vm"
image = "images:rockylinux/8/cloud"
ram = "2GB"
cpu = 2
protected = 0
secureboot = 1

[lab-ubuntu22-1]
type = "vm"
image = "ubuntu:22.04"
ram = "2GB"
cpu = 2
protected = 0
secureboot = 1