[lab-rocky8-1-ct]
type = "container"
image = "images:rockylinux/8/cloud"
ram = "1GB"
cpu = 1
protected = 0
secureboot = 1

[lab-rocky8-2-ct]
type = "container"
image = "images:rockylinux/8/cloud"
ram = "1GB"
cpu = 1
protected = 0
secureboot = 1

[lab-rocky8-1-vm]
type = "vm"
image = "images:rockylinux/8/cloud"
ram = "1GB"
cpu = 1
protected = 0
secureboot = 1

[lab-rocky8-3-ct]
type = "container"
image = "images:rockylinux/8/cloud"
ram = "1GB"
cpu = 1
protected = 0
secureboot = 1

[lab-rocky8-2-vm]
type = "vm"
image = "images:rockylinux/8/cloud"
ram = "1GB"
cpu = 1
protected = 0
secureboot = 1

[lab-alma8-1-ct]
type = "container"
image = "images:almalinux/8/cloud"
ram = "1GB"
cpu = 1
protected = 0
secureboot = 1

[lab-alma8-2-vm]
type = "vm"
image = "images:almalinux/8/cloud"
ram = "1GB"
cpu = 1
protected = 0
secureboot = 1