[lab-alma9-2-ct]
type = "container"
image = "images:almalinux/9/cloud"
ram = "2GB"
cpu = 2
protected = 0
secureboot = 1

[lab-rocky8-3-ct]
type = "container"
image = "images:rockylinux/8/cloud"
ram = "2GB"
cpu = 2
protected = 0
secureboot = 1

[lab-rocky9-3-ct]
type = "container"
image = "images:rockylinux/9/cloud"
ram = "2GB"
cpu = 2
protected = 0
secureboot = 1

[lab-debian13-1-ct]
type = "container"
image = "images:debian/13/cloud"
ram = "2GB"
cpu = 2
protected = 0
secureboot = 1

[lab-ubuntu24-1-ct]
type = "container"
image = "ubuntu:24.04"
ram = "4GB"
cpu = 4
protected = 0
secureboot = 1
