---
- name: Setup Lab
  hosts: lab
  serial: 1
  become: true
  ignore_unreachable: true
  ignore_errors: true
  tasks:
    - name: Update OS
      ansible.builtin.dnf:
        name: "*"
        state: latest
    - name: Pause for 30 seconds
      ansible.builtin.pause:
        seconds: 30
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux'
    - name: Reboot
      ansible.builtin.reboot:
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux'
